import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next Recap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between p-3 text-lg font-semibold bg-blue-700">
          <h2>NEXT</h2>
          <div className="flex">
            <h3>about</h3>
            <h3>service</h3>
            <h3>contact</h3>
          </div>
        </nav>
        <div className="h-screen">{children}</div>
        <footer>
          <h1 className="text-center text-2xl bg-blue-700">Copyrights reserved</h1>
        </footer>
      </body>
    </html>
  );
 }
